name: iOS Pull Request Workflow

on:
  pull_request:
    branches: [ master, develop ]
  push:
    branches: [ master, develop ]
    
jobs:
  build:
    name: Test desafio App
    runs-on: macos-latest

    steps:
      - name: Bundler CLI
        uses: CultureHQ/actions-bundler@v1.0.0
        with:
          args: 'install'
      
      - name: Fastlane Action
        uses: maierj/fastlane-action@v2.0.1
        with:
          lane: 'unit_test'


