name: iOS Pull Request Workflow

on:
  pull_request:
    branches: [ master, develop ]
  push:
    branches: [ master, develop ]
    
jobs:
  build:
    name: Test desafio App
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      
      - name: Fastlane Action
        uses: maierj/fastlane-action@v2.0.1
        with:
          lane: 'unit_test'


